// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Todo.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GPBTimestamp;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TodoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface TodoRoot : GPBRootObject
@end

#pragma mark - Todo

typedef GPB_ENUM(Todo_FieldNumber) {
  Todo_FieldNumber_Tid = 1,
  Todo_FieldNumber_Title = 2,
  Todo_FieldNumber_Detail = 3,
  Todo_FieldNumber_Type = 4,
  Todo_FieldNumber_Timestamp = 5,
  Todo_FieldNumber_Delete_p = 6,
  Todo_FieldNumber_Done = 7,
};

GPB_FINAL @interface Todo : GPBMessage

@property(nonatomic, readwrite) int64_t tid;

@property(nonatomic, readwrite) BOOL hasTid;
@property(nonatomic, readwrite, copy, null_resettable) NSString *title;
/** Test to see if @c title has been set. */
@property(nonatomic, readwrite) BOOL hasTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *detail;
/** Test to see if @c detail has been set. */
@property(nonatomic, readwrite) BOOL hasDetail;

@property(nonatomic, readwrite, copy, null_resettable) NSString *type;
/** Test to see if @c type has been set. */
@property(nonatomic, readwrite) BOOL hasType;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *timestamp;
/** Test to see if @c timestamp has been set. */
@property(nonatomic, readwrite) BOOL hasTimestamp;

@property(nonatomic, readwrite) BOOL delete_p;

@property(nonatomic, readwrite) BOOL hasDelete_p;
@property(nonatomic, readwrite) BOOL done;

@property(nonatomic, readwrite) BOOL hasDone;
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
